### ISSUE TITLE
如何生成注释？

### ISSUE THREAD

**Issue by zhaojie** [yuzukwok/Abp.Web.Api.SwaggerTool#1]
HI，
是否支持生成xml注释文档

**Comment by yuzukwok** [comment]
1.在源代码中对参数，方法使用xml注释，编译DLL选择同时生成xml文件
2.abp.web.api.swaggertool配置文件中配置  "XmlCommentFiles": ["xxx.xml"]//xml注释的文件名

**Comment by zhaojie** [comment]
@yuzukwok  
<img width="701" alt="qq20161105-0 2x" src="https://cloud.githubusercontent.com/assets/851162/20030087/91e4a8bc-a398-11e6-8001-df06e3ea1c30.png"> 
再请教下，截图这块的注释怎么加的？

**Comment by zhaojie** [comment]
@yuzukwok  swagger/docs/v1 这个请求 tags:[] 是空

**Comment by yuzukwok** [comment]
如图的注释 确实是对应swagger 中Tags的部分。而这部分生成通过扩展实现
Abp.Web.Api.SwaggerTool/Abp.Web.Api.SwaggerTool/ApplyDocumentVendorExtensions.cs  

看Controller的上对应的DisplayNameAttribute

**Comment by zhaojie** [comment]
@yuzukwok  在AppService加上DisplayNameAttribute ，测试了下 不会生成对应的tags

**Comment by zhaojie** [comment]
@yuzukwok  abp的dynamic controller 是根据iappservice 接口来定义 ,接口是不允许加displayname ，所以要换成description ，
 var controllers = apiExplorer.ApiDescriptions.Select(p => p.ActionDescriptor.ControllerDescriptor).Distinct().ToList();
            foreach (var item in controllers)
            {
                var desc = item.GetCustomAttributes<DisplayNameAttribute>();
                if (desc != null && desc.Count > 0)
                {
                    swaggerDoc.tags.Add(new Tag() { name = item.ControllerName, description = desc[0].DisplayName });
                }
                else
                {
                    var descattr = item.GetCustomAttributes<DescriptionAttribute>();
                    if (descattr != null && descattr.Count > 0)
                    {
                        swaggerDoc.tags.Add(new Tag() { name = item.ControllerName, description = descattr[0].Description });
                    }
                }
            }

**Comment by zhaojie** [comment]
@yuzukwok  可以在   nuget fixed 一下么

**Comment by yuzukwok** [comment]
OK

**Comment by zhaojie** [comment]
Thanks
